version: '3.8'
services:
  backend:
    build: Dockerfile
    expose:
      - 8000
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql

volumes:
  - ./postgres-data
  
    