# Generated by Django 4.2 on 2024-01-14 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_cart_user'),
        ('payment', '0002_alter_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('cartitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='food.cartitem')),
            ],
            bases=('food.cartitem',),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
